version: '3.8'

services:
  my-portfolio:
    container_name: my-portfolio
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
#    expose:
#      - 9006:9006
#    ports:
#      - "9006:9006"
    restart: unless-stopped
    networks:
      - bible-project-network

networks:
  bible-project-network:
    external: true
