version: '3'

services:
  lucutovidiuproject:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    expose:
      - '8080'
    networks:
      - jetty-plus

networks:
  jetty-plus:
    external: true
