version: '3'

services:
  port-nginx:
    container_name: port-nginx-image
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "443:443"
    networks:
      - jetty-plus

networks:
  jetty-plus:
    external: true
